name: "Run type checker"
on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - "src/**"
      - "tests/**"
      - "pyproject.toml"
      - "poetry.lock"
      - "nix/**"
      - "flake.nix"
      - "flake.lock"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: install Poetry dependencies
        run: nix develop --command poetry install --with dev,examples

      - name: Run check
        run: nix develop --command poetry run  make check
